In [136]:
import numpy as np # linear algebra
import pandas as pd # data processing
import math

In [137]:
#data is the movie rating by users
#Rows define movies
#Columns define users
#row,column pair defines ratings given by user
#PROBLEM IS TO PREDICT RATINGS FOR MOVIES WHICH A USER HAS NOT GIVEN ANY RATINGS
data = pd.read_csv('../input/recommendation.csv')

In [138]:
data.head()

Alice  Bob  Carol  Dave
0    5.0  5.0    0.0   0.0
1    5.0  NaN    NaN   0.0
2    NaN  4.0    0.0   NaN
3    0.0  0.0    5.0   4.0
4    0.0  0.0    5.0   NaN

In [139]:
no_movies = len(data['Alice'])

In [140]:
no_users = len(data.columns)
no_users

4

In [141]:
#X for every movie has 3 Parameters: 1, Romance, Action
#Initializing X with small random values
X = np.random.uniform(low=0.01, high=0.25, size=(3,no_movies))
X[0,:] = 1
X

array([[1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.14934099, 0.1968444 , 0.01773699, 0.24895188, 0.13012068],
       [0.16493554, 0.12649649, 0.09518619, 0.09822578, 0.12157328]])

In [142]:
#Every User has similarly 3 coefficients
#Initializing theta with small random values
theta = np.random.uniform(low=0.01, high=0.25, size=(3,no_users))

In [143]:
#sumx to temporarily store values
sumx = np.zeros((3,1))
sumx = sumx+sumx
sumx

array([[0.],
       [0.],
       [0.]])

In [144]:
#Gradient Descent without regularization
for repeat in range(500):
    for j in range(no_users):
        for i in range(no_movies):
            sumx = np.zeros((3,1))
            for k in range(no_users):
                if(math.isnan(data.iloc[i,k])==False):
                    sumx[:,0] = sumx[:,0] + (np.dot(theta[:,k],X[:,i])-data.iloc[i,k])*theta[:,k]
                
            X[:,i:i+1]=X[:,i:i+1]-0.05*(sumx)
            sumx = np.zeros((3,1))
            for l in range(no_movies):
                if(math.isnan(data.iloc[l,j])==False):
                    sumx[:,0] = sumx[:,0] + (np.dot(theta[:,j],X[:,l])-data.iloc[l,j])*X[:,l]
        theta[:,j:j+1]=theta[:,j:j+1]-0.05*(sumx)
        sumx = np.zeros((3,1))


In [145]:
#After Gradient Descent X Value
X

array([[ 2.31521615,  2.59099115,  1.89708091,  1.27890598,  1.48162629],
       [ 0.79038359,  0.2307523 ,  0.47129254,  1.1190585 ,  0.39211142],
       [ 1.4904065 ,  1.29509407,  1.18893388, -2.41456354, -2.4298921 ]])

In [146]:
#After Gradient Descent theta Value
theta

array([[ 1.42970718,  1.42965271,  0.86416669,  0.49522968],
       [ 0.37894869,  0.37908427,  0.27233776,  0.62892745],
       [ 0.93290314,  0.93291472, -1.48683193, -1.10282507]])

In [148]:
#Predicted User Ratings
#Note: -0 Means very small negative value
for j in range(no_movies):
    for i in range(no_users):
        predict = np.dot(theta[:,i],X[:,j])
        print(" %6.1f " % predict,end='  ')
    print()

    5.0       5.0      -0.0       0.0   
    5.0       5.0       0.4      -0.0   
    4.0       4.0       0.0      -0.1   
   -0.0       0.0       5.0       4.0   
    0.0      -0.0       5.0       3.7   
